# Example awm config

[startup]
exec = ["xwayland-satellite", "hyprpaper"]
env = [
    { XDG_CURRENT_DESKTOP = "awm" },
    { DISPLAY = ":0" },
    { MOZ_ENABLE_WAYLAND = 1 },
    { EXAMPLE = "true" },
]

[binds]
exit = "Alt Escape"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.move = "Alt m"
window.up = "Alt k"
window.down = "Alt j"
window.left = "Alt h"
window.right = "Alt l"
window.swap.up = "Alt Shift K"
window.swap.down = "Alt Shift J"
window.swap.left = "Alt Shift H"
window.swap.right = "Alt Shift L"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"
# modifiers: "Shift", "Caps", "Control", "Alt", "Mod2", "Mod3", "Logo", "Mod5",

# name, width, height and refresh are required fields
# monitors do not need to be in the config to function
[[monitors]]
name = "HDMI-A-1"
enabled = true     # set to true by default
width = 1920
height = 1080
refresh = 60.0
x = 0
y = 0
transform = "none" # "none", "90", "180", "270", "f", "f90", "f180", f270"
scale = 1.0
adaptive = false   # adaptive sync

[[monitors]]
name = "WL-1"
enabled = true
width = 1024
height = 768
refresh = 60.0

[[monitors]]
name = "eDP-1"
width = 2880
height = 1800
refresh = 90.0

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"

# TODO: keyboard, locale
