# Example awm config

[startup]
exec = [
    "xwayland-statellite",
    "swaybg --color 1F1F1F"
]
env = [
    { "EXAMPLE" = "true" },
    { "EXAMPLE2" = 122 },
]

[binds]
exit = "Alt Escape"
window.fullscreen = "Alt F"
window.previous = "Alt O"
window.next = "Alt P"
workspace.tile = "Alt T"
workspace.open.digit = "Alt digit"
workspace.window_to.digit = "Alt Shift digit"

[[commands]] # Launcher
bind = "Alt Space"
exec = "rofi -drun show"

[[commands]] # Screenshot
bind = "Alt C"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

# TODO: keyboard, locale, monitor configuration
