# Example awm config

[startup]
exec = [
    "xwayland-satellite"
]
env = [
    { "EXAMPLE" = "true" },
    { "DISPLAY" = ":1" },
]

[binds]
exit = "Alt Escape"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"

[[commands]] # Launcher
bind = "Alt space"
exec = "wofi --show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"

# TODO: keyboard, locale, monitor configuration
