# Example awm config

[startup]
exec = ["xwayland-satellite", "hyprpaper"]
env = [
    { XDG_CURRENT_DESKTOP = "awm" },
    { DISPLAY = ":0" },
    { MOZ_ENABLE_WAYLAND = 1 },
    { EXAMPLE = "true" },
]

[binds]
exit = "Alt Escape"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.move = "Alt m"
window.up = "Alt k"
window.down = "Alt j"
window.left = "Alt h"
window.right = "Alt l"
window.swap.up = "Alt Shift K"
window.swap.down = "Alt Shift J"
window.swap.left = "Alt Shift H"
window.swap.right = "Alt Shift L"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"

[[monitors]]
name = "HDMI-A-1"
enabled = true
width = 1920
height = 1080
refresh = 60.0

[[monitors]]
name = "WL-1"
enabled = true
width = 1280
height = 720
refresh = 60.0
transform = "f180"

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"

# TODO: keyboard, locale
