# Example awm config

# place your config at ~/.config/awm/config.toml
# or specify a config path with the -c flag

[startup]
exec = ["xwayland-satellite", "hyprpaper"] # list of commands to run on startup

# env variables to set on startup
[[startup.env]]
XDG_CURRENT_DESKTOP = "awm"
DISPLAY = ":0"
MOZ_ENABLE_WAYLAND = 1
ELECTRON_OZONE_PLATFORM_HINT = "wayland"

[exit]
exec = ["echo \"exiting awm\""] # list of commands to run on exit

[keyboard] # default keyboard layout, optional
layout = "us"
model = "pc105"
variant = ""
options = ""
repeat_rate = 25
repeat_delay = 600

[binds] # default binds which can be overwitten in your config
exit = "Alt Escape"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.move = "Alt m"
window.up = "Alt k"
window.down = "Alt j"
window.left = "Alt h"
window.right = "Alt l"
window.swap.up = "Alt Shift K"
window.swap.down = "Alt Shift J"
window.swap.left = "Alt Shift H"
window.swap.right = "Alt Shift L"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"
# modifiers: "Shift", "Caps", "Control", "Alt", "Mod2", "Mod3", "Logo", "Mod5",
# Number is a special token that will be replaced with the number key pressed

# name, width, height and refresh are required fields
# monitors do not need to be in the config to function
[[monitors]]
name = "HDMI-A-1"
enabled = true     # true by default
width = 1920
height = 1080
refresh = 60.0
x = 2560           # 0 by default
y = 720            # 0 by default
transform = "none" # "none", "90", "180", "270", "f", "f90", "f180", f270"
scale = 1.0        # 1.0 by default
adaptive = false   # adaptive sync, false by default

[[monitors]]
name = "DP-1"
width = 2560
height = 1440
refresh = 180.0

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"
